### ISSUE TITLE
A little bug alongside a suggestion 

### ISSUE THREAD

**Issue by jaylac2000** [Wumpotamus/UHC#17]
on a lot of servers /sc = /sctaffchat ....

maybe make your /sc for this plugin /sce instead ??

However this plugin **doesnt** overwrite my /sc for staffchat but it pay for other people

**Comment by jaylac2000** [comment]
also maybe make /heal be /uhcheal instead. because i have my servers main core on my new UHC server using your plugin which has this command already but it doesnt overwrite

**Comment by buchwasa** [comment]
Hey there! I'll consider changing some of these, but for now, a way to workaround your problem is to do `/uhc:sc` or `/uhc:heal`.

**Comment by jaylac2000** [comment]
ok ,ty

**Comment by jaylac2000** [comment]
best public uhc plugin for mcpe made yet
