### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by jaylac2000** [Wumpotamus/UHC#19]
add configurable options . add command permissions to plugin.yml (makes it easier to locate). 

like how much players are needed for a game to auto start

configurable timer changes for start, end, pvp enable etc

spawn area / safe zone

default-global-mute: true or false

**Comment by buchwasa** [comment]
I will add the ability to configure timers for release 1.0.0.
Auto start will not be added to this, since this is for hosted UHCs, I may consider changing that in the future.
Elaborate on a safe zone please.
I will also consider adding configurable defaults.

**Comment by jaylac2000** [comment]
maybe, config option, or auto or hosted?
