### ISSUE TITLE
ScoreFactory not found

### ISSUE THREAD

**Issue by Willoxey** [Wumpotamus/UHC#24]
Pmmp version: 3.14.1

Running from source(cuz i cant get the .phar)

I've already tried installing the virion of scorefactory, but i keep getting the same error. Any help?

Error:
`11.07 03:01:25 [Server] Server thread/CRITICAL Error: "Class 'JackMD\ScoreFactory\ScoreFactory' not found" (EXCEPTION) in "plugins/UHC-master/src/uhc/game/GameHeartbeat" at line 247
11.07 03:01:25 [Server] Server thread/DEBUG #0 plugins/UHC-master/src/uhc/game/GameHeartbeat(86): uhc\game\GameHeartbeat->handleScoreboard(object pocketmine\Player)
11.07 03:01:25 [Server] Server thread/DEBUG #1 plugins/UHC-master/src/uhc/game/GameHeartbeat(61): uhc\game\GameHeartbeat->handlePlayers()
11.07 03:01:25 [Server] Server thread/DEBUG #2 src/pocketmine/scheduler/TaskHandler(134): uhc\game\GameHeartbeat->onRun(integer 281)
11.07 03:01:25 [Server] Server thread/DEBUG #3 src/pocketmine/scheduler/TaskScheduler(179): pocketmine\scheduler\TaskHandler->run(integer 281)
11.07 03:01:25 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 281)
11.07 03:01:25 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2391): pocketmine\plugin\PluginManager->tickSchedulers(integer 281)
11.07 03:01:25 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2154): pocketmine\Server->tick()
11.07 03:01:25 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
11.07 03:01:25 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1588): pocketmine\Server->start()
11.07 03:01:25 [Server] Server thread/DEBUG #9 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
11.07 03:01:25 [Server] Server thread/DEBUG #10 src/pocketmine/PocketMine(304): pocketmine\server()
11.07 03:01:25 [Server] Server thread/DEBUG #11 (11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)
11.07 03:01:25 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
11.07 03:01:25 [Server] Server thread/EMERGENCY Please upload the "/crashdumps/Sat_Jul_11-03.01.25-UTC_2020.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.`

**Comment by buchwasa** [comment]
You're using the outdated ScoreFactory, the new one is https://poggit.pmmp.io/ci/stephen-mc-pl/ScoreFactory, build 11 is what you'd want for PM3.
