### ISSUE TITLE
Nothing Dealing with the Plugin

### ISSUE THREAD

**Issue by ghost** [Wumpotamus/UHC#28]
Hello I have been seeing your plugin and I want to make a shrinking border with my Team UHC plugin any idea how?

**Comment by buchwasa** [comment]
Hey there, you can look into my border implementation, specifically the Border->build() on master branch. If you want to take the implementation as a whole, feel free, what I do suggest if you take that (or make a border in general) is to put it in a closure task to help reduce the strain it puts on the server. If you do make your own implementation, not even to advertise, but you should use a virion like libChunkLoader to load the chunks before you go throwing blocks in them. If you need a more in depth explanation or anything else on the matter, you can comment on here.

**Comment by ghost** [comment]
Can I use that border.php to do the border as well

**Comment by buchwasa** [comment]
Sure, my PM4 branch has a better looking Border.php, if you're willing to port that back to PM3 for yourself.

**Comment by ghost** [comment]
Ok. Is it ok if I can send my code to you can see where to add the border making commands?

**Comment by buchwasa** [comment]
I don't need to see anything, it's relatively easy to change the border size and build it. In your main file, you construct the border class, add a getter or a variable, then in your command, you do Border->setSize() and Border->build().

**Comment by ghost** [comment]
Ok that should be easy thanks :)

**Comment by ghost** [comment]
One more question how can I turn off natural regeneration In game?

**Comment by buchwasa** [comment]
See https://github.com/stephen-mc-pl/UHC/blob/master/src/uhc/EventListener.php#L77-L82

**Comment by ghost** [comment]
🙏
