### ISSUE TITLE
ScoreFactory Class not found

### ISSUE THREAD

**Issue by lighting1210** [Wumpotamus/UHC#35]
i don't know much about virions and libraries but using the latest code from the github page doesn't have it built in, i could be just dumb but still felt like making an issues cause u might not be aware of this bug if u can even call it that

**Comment by buchwasa** [comment]
Poggit builds the phars with the virions injected, so there's no need to include them on the GitHub. https://poggit.pmmp.io/ci/buchwasa/UHC/UHC
