### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by buchwasa** [Wumpotamus/UHC#4]

**Comment by buchwasa** [comment]
Whilst working on this, I've decided it will be best to not officially support changing team sizes within the plugin, but rather have a scenario handle that. There will still be a team command and I am planning on releasing a To2 scenario alongside a new version of Scenarios Pack 1.

**Comment by jaylac2000** [comment]
add configurable options for this

examples 

teams: true or false
amount-of-teams: 6 (amount)
max-per-team: 3

**Comment by buchwasa** [comment]
The main stuff of this should be done, however, it is not configurable, so this issue is still open.
