### ISSUE TITLE
Detailed README

### ISSUE THREAD

**Issue by buchwasa** [Wumpotamus/UHC#9]

**Comment by Johnsonk79** [comment]
I feel like the priority on this one should be higher because rn idk what this plugin can do and how i can setup :)

**Comment by eloklam** [comment]
I think further documentation is not that needed since the code can easily being read in this plugin. 💩

**Comment by Johnsonk79** [comment]
That is for people who actually know how to code 💩

**Comment by buchwasa** [comment]
I'm working on it as we speak

**Comment by buchwasa** [comment]
That should cover the basics @Johnsonk79. Let me know if you need me to cover more.
